# Server Configuration
server.port=8085
server.servlet.context-path=/

# Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL Database Configuration (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Datasource Initialization
spring.jpa.defer-datasource-initialization=false

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=false

# Application Name
spring.application.name=API Restaurante

# Logging
logging.level.root=INFO
logging.level.br.com.tech.challenger=DEBUG
logging.level.org.flywaydb=INFO
